version: '3'

vars:
  REPOSITORY_NAME: jokechat
  APP_NAME: guid
  APP_VERSION: v1.0.3
  PRIVATE_DOCKER_HUB: uhub.service.ucloud.cn
tasks:
  print:
    cmds:
      - echo "build all platform!"
  clean:
    cmds:
      - rm -rf release
      - mkdir -p release

  build-tpl:
    label: build-{{.TASK}}
    cmds:
      - |
        GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOMIPS={{.GOMIPS}} GOAMD64={{.GOAMD64}} \
        go build -o release/{{.APP_NAME}}_{{.TASK}}

  docker_build_linux_arm64:
    cmds:
      - task: build-tpl
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: arm64
        }
      - docker build --platform=linux/arm64 --build-arg RELEASE_NAME={{.APP_NAME}}_{{.TASK}}  --tag {{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}} .
  docker_build_linux_amd64:
    cmds:
      - task: build-tpl
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v4
        }
      - docker build --platform=linux/amd64 --build-arg RELEASE_NAME={{.APP_NAME}}_{{.TASK}}  --tag {{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}} .

  docker_build_arm_amd_push:
    cmds:
      - task docker_build_linux_arm64 docker_build_linux_amd64
      - docker push {{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}}
      - docker push {{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}}
      - docker manifest create {{.REPOSITORY_NAME}}/{{.APP_NAME}}:{{.APP_VERSION}} {{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}} {{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}}
      - docker manifest push {{.REPOSITORY_NAME}}/{{.APP_NAME}}:{{.APP_VERSION}}
  docker_uhub_push:
    cmds:
      - docker tag {{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}} {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}}
      - docker tag {{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}} {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}}
      - docker push {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}}
      - docker push {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}}
      - docker manifest create {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}:{{.APP_VERSION}} {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}-arm64:{{.APP_VERSION}} {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}-amd64:{{.APP_VERSION}}
      - docker manifest push {{.PRIVATE_DOCKER_HUB}}/{{.REPOSITORY_NAME}}/{{.APP_NAME}}:{{.APP_VERSION}}

  default:
    cmds:
      - task: print
      - task: clean
      - task: docker_build_arm_amd_push
#      - task: docker_uhub_push